remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

title: Andy's Blog
